### ISSUE TITLE
[bug] eval sometimes applies result to selector and root document

### ISSUE THREAD

**Issue by jimschubert** [jimschubert/yizzy#1]
**Summarize the bug**

When using `eval` in combination with `selector` and `value_type` as done in https://github.com/jimschubert/yizzy/blob/master/testdata/operations/use_envs.yaml, the the resulting document applies the last operation to both `selector` and the document root (see https://github.com/jimschubert/yizzy/blob/master/testdata/expectations/expect_use_envs.yaml).

**To Reproduce**

Input file:

```
!<tag:clarkevans.com,2002:invoice>
# Example taken from https://yaml.org/spec/1.2/spec.html#id2761803
# comments changed to string block due to yaml lib converting the example to a one-liner string.
invoice: 34843
date: 2001-01-23
bill-to: &id001
  given: Chris
  family: Dumars
  address:
    lines: |
      458 Walkman Dr.
      Suite #292
    city: Royal Oak
    state: MI
    postal: 48046
ship-to: *id001
product:
  - sku: BL394D
    quantity: 4
    description: Basketball
    price: 450.00
  - sku: BL4438H
    quantity: 1
    description: Super Hoop
    price: 2392.00
tax: 251.42
total: 4443.52
comments: |
  Late afternoon is best.
  Backup contact is Nancy
  Billsmer @ 338-4338.
```

Migration:

```
operations:
  - selector: .ship-to
    eval: '.full_name = strenv(FIRST_NAME) + " " + strenv(LAST_NAME)'
    value_type: '!!str'
  - selector: .ship-to
    eval: '.co = strenv(LITERAL_ENV)'
    value_type: '!!str'
env:
  FIRST_NAME: .bill-to.given
  LAST_NAME: .bill-to.family
  LITERAL_ENV: '"Jim Schubert"'
```

Then, run for example:

```
yizzy -f invoice.yaml -d migrations --in-place
```

This modifies the file like so:

```diff
diff --git a/invoice.yaml b/invoice.yaml
index b4c79a8..9a8dfec 100644
--- a/invoice.yaml
+++ b/invoice.yaml
@@ -3,7 +3,7 @@
 # comments changed to string block due to yaml lib converting the example to a one-liner string.
 invoice: 34843
 date: 2001-01-23
-bill-to: &id001
+bill-to: &id001 !!str
   given: Chris
   family: Dumars
   address:
@@ -13,6 +13,8 @@ bill-to: &id001
     city: Royal Oak
     state: MI
     postal: 48046
+  full_name: Chris Dumars
+  co: Jim Schubert
 ship-to: *id001
 product:
   - sku: BL394D
@@ -29,3 +31,4 @@ comments: |
   Late afternoon is best.
   Backup contact is Nancy
   Billsmer @ 338-4338.
+co: Jim Schubert

```

**Expected behavior**

The last `co: Jim Schubert` should not exist.

**Additional context**

Notice that `co` is also added to the reference target (`.bill-to`) rather than manipulating the document with a `!!merge` reference and applying the property accordingly. The `!!str` type is also applied to `.bill-to` rather than only `.co` and `.full_name` as expected. The code _does_ apply `!!str` to these nodes, otherwise yq would explicitly add the type.
